version: '3'
volumes: 
  platzhalterio-data:

services:

  platzhalterio:
    container_name: platzhalterio
    image: composeus/platzhalterio:latest
    restart: unless-stopped
    environment:
      DB_PASSWORD: "abcd"
      DB_HOST: "postgres"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.platzhalterio.rule=Host(`beta.platzhalter.io`)"
      - "traefik.http.routers.platzhalterio.entrypoints=web,websecure"
      - "traefik.http.routers.platzhalterio.tls.certresolver=leresolver"
    links:
      - "postgres:postgres"
    ports:
      - "0.0.0.0:8080:80"

  postgres:
    container_name: postgres
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "abcd"
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - platzhalterio-data:/var/lib/postgresql/data
